### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by larsbrinkhoff** [gnooth/feline#1]
Does it have a name?

**Comment by gnooth** [comment]
Not yet, but soon.

**Comment by gnooth** [comment]
Feline

**Comment by larsbrinkhoff** [comment]
Thanks!

Do you have any particular application in mind for your Forth?

**Comment by gnooth** [comment]
No, I'm not really much of an application programmer. I'm more interested in improving performance and extending the capabilities of the language.

**Comment by honix** [comment]
Is there is code examples or some short feature list of Feline lang?

**Comment by gnooth** [comment]
Not yet. It's early, and the language is still changing.

**Comment by honix** [comment]
Okay, man. Wish you super speed as C and good abstraction as Lisp. :)
